### ISSUE TITLE
Implement Advanced Search with ElasticSearch

### ISSUE THREAD

**Issue by Josue19-08** [OFFER-HUB/offer-hub#78]
## 📘 Description  
The current search system needs to be optimized using **ElasticSearch** to enable faster and more precise searches for `services` and `users`. This will allow dynamic filtering, keyword-based searches, and better ranking of results.  

### **Key Features:**  
- **Set up ElasticSearch** as a service in the backend.  
- **Synchronize data** between PostgreSQL and ElasticSearch to keep search indexes updated.  
- **Implement search endpoints** with filters such as name, category, price, and rating.  

### **Implementation Details:**  

1. **Configure ElasticSearch in Docker:**  
   - Add an `elasticsearch` service in `docker-compose.yml`:  
     ```yaml
     services:
       elasticsearch:
         image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
         environment:
           - discovery.type=single-node
           - xpack.security.enabled=false
         ports:
           - "9200:9200"
     ```
   - Ensure the backend can **connect to ElasticSearch** on `http://elasticsearch:9200`.  

2. **Index relevant data in ElasticSearch:**  
   - Modify `src/modules/services/services.service.ts` to:  
     - **Insert new services** into the index.  
     - **Update records** when a service is modified.  
     - **Remove records** when a service is deleted.  

3. **Implement optimized search endpoints:**  
   - Create `src/modules/search/search.service.ts` to handle queries.  
   - Enable **search by keyword, category, price range, and rating**.  
   - Implement **pagination and sorting** in the search results.  

4. **Validate and test performance:**  
   - Ensure queries return **relevant and ranked results**.  
   - Optimize queries to **reduce unnecessary searches**.  

---

## ✅ Acceptance Criteria  
- [ ] `docker-compose.yml` includes an `elasticsearch` service.  
- [ ] Services and users are indexed correctly in ElasticSearch.  
- [ ] A new module `src/modules/search/` is created to handle search logic.  
- [ ] Search endpoints return **filtered and paginated results**.  
- [ ] Implemented filters: keyword, category, price range, rating.  
- [ ] Attach screenshots of ElasticSearch indexing logs.  
- [ ] Attach screenshots of test results confirming search functionality.  

---

⚠ Do not apply until the ODHack begins, if you apply before we will not review your applications.  

⚠ Read our main readme and our guidelines before applying.
